name: Tests unitaire de l'app
on: push 
env: 
  APP_VERSION: 1.0.0
jobs: 
  Tests-app: 
    runs-on: ubuntu-latest
    steps: 
      - name: Récuperation du repository
        uses: actions/checkout@v3
      - name: Installation de nodeJS 
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Info sur la version testé
        run: echo ${{ matrix.node-version }}
      - name: Installation des dépendances
        run: npm install
      - name: Execution des tests unitaire 
        run: npm test
      - name: Execution du code coverage
        run: npm run cover
      - name: Récupération du rapport
        uses: actions/upload-artifact@v3
        with:
          name: reports 
          path: ./reports/**
  build-app:
    needs: Tests-app
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du repo
        uses: actions/checkout@v3
      - name: Installation de QEMU
        uses: docker/sutup-qemu-action@v1
      - name: Installation de docker BuildX
        uses: docker/sutup-buildx-action@
      - name: Login au docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}
      - name: Build & push docker
        uses: docker/build-puch-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME}}/weather:${{ env.APP_VERSION }}